#!/usr/bin/env bash
source ~/.bashrc
conda activate deeplearning
OPENAI_LOG_FORMAT='stdout,log,csv,tensorboard' OPENAI_LOGDIR=/scratch/cluster/dsbrown/tflogs/human_qbert20env_$1 python -m baselines.run --alg=ppo2 --env=QbertNoFrameskip-v4 --custom_reward pytorch --custom_reward_path /u/dsbrown/Code/learning-rewards-of-learners/learner/learned_models/qbert_human.params --num_timesteps=4e7 --save_interval=200 --num_env 20 --seed $1
