#!/usr/bin/env bash
source ~./bashrc
conda activate deeplearning
OPENAI_LOG_FORMAT='stdout,log,csv,tensorboard' OPENAI_LOGDIR=/scratch/cluster/dsbrown/tflogs/seaquest_$1 python -m baselines.run --alg=ppo2 --env=SeaquestNoFrameskip-v4 --custom_reward pytorch --custom_reward_path /u/dsbrown/Code/learning-rewards-of-learners/learner/learned_models/seaquest_12_5_sorted_pref.params --num_timesteps=1e4 --save_interval=5 --seed $1

