#!/usr/bin/env python

"""
A very simple wrapper for a function call, making a corresponding condor script
and submitting it.
"""

import os, sys
from datetime import datetime
from pathlib import Path

TEST = True

job_desc = """
+Group   = "GRAD"
+Project = "AI_ROBOTICS"
+ProjectDescription = "."
+GPUJob = true

universe = vanilla
Requirements = (TARGET.GPUSlot) && (CUDAGlobalMemoryMb >= 10000) && NumJobStarts == 0
request_GPUs = 1

notify_user = dsbrown
Notification = Complete

getenv = true

Executable = run_atari_rl
Arguments = $(Process) seaquest

Error = /scratch/cluster/dsbrown/CondorOutput/seaquest_$(Process)_err
Output = /scratch/cluster/dsbrown/CondorOutput/seaquest_$(Process)_out
Log = /scratch/cluster/dsbrown/CondorOutput/seaquest_$(Process)_condor.log

Queue 2
"""

if TEST:
    print(job_desc)
else:
    proc = subprocess.Popen('condor_submit', stdin=subprocess.PIPE)
    proc.stdin.write(job_desc)
    proc.stdin.close()
