#!/usr/bin/env bash
source ~/.bashrc
conda activate deeplearning
cd ../learner/
python LearnAtariNoviceSnippetsSortedTimePrefs.py --models_dir /scratch/cluster/dsbrown --env_name pong --reward_model_path ./learned_models/pong_timepref.params