#!/usr/bin/env bash
source ~/.bashrc
conda activate deeplearning
cd ../learner/
python LearnAtariNoviceSnippetsSortedTimePrefs.py --models_dir /scratch/cluster/dsbrown --env_name beamrider --reward_model_path ./learned_models/beamrider_timepref.params