#!/usr/bin/env bash
source ~/.bashrc
conda activate deeplearning
cd ../learner/
python LearnAtariHumanSnippetsSorted.py --env_name spaceinvaders --reward_model_path ./learned_models/spaceinvaders_human.params --data_dir /scratch/cluster/dsbrown/atari_v1/